### ISSUE TITLE
Node deprecation warning for Punycode

### ISSUE THREAD

**Issue by aaronkyle** [observablehq/framework#1445] opened 2024-06-10 01:30 UTC
Node.js v22.2.0 documentation lists punycode as deprecated:
https://nodejs.org/api/punycode.html

However Framework uses this package:
https://github.com/observablehq/framework/blob/e4682b3afb4807f863bcd76f0858a8af0c3432a0/src/node.ts#L197

When running commands, I continually encounter this warning:

```
(node:42713) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

It would be great if we could find a way to avoid seeing this warning.

**Comment by mbostock** [comment] 2024-06-10 23:32
Framework doesn’t use punycode directly. The line you linked to is a list of Node’s built-in packages and is used for resolving node imports.

I traced the dependency to the [psl](https://github.com/lupomontero/psl) library. The dependency chain is:

@observablehq/framework → jsdom@^23.2.0 → tough-cookie@^4.1.3 → psl@^1.1.33

This was fixed in https://github.com/lupomontero/psl/pull/298, but a new version of psl has not been published in two years, so it’s unclear if this will be fixed anytime soon. At any rate, the problem is not within this library, and unless we’re willing to drop the dependency on JSDOM. This may also be fixed by tough-cookie in https://github.com/salesforce/tough-cookie/pull/346, but it is waiting for a v5 release.

**Closed by mbostock** 2024-06-10 23:32 UTC
