### ISSUE TITLE
import and bundle npm:*css from style.css?

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#1195] opened 2024-04-03 16:12 UTC
You can hot link a style sheet in style.css, with its full url, for example:
`@import url("https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.css");`
but the sheet will not be imported and copied into your own stylesheet.

Alternatively, you can link from a page (`page.md`):
`<link rel="stylesheet" href="npm:leaflet/dist/leaflet.css">`
This will be served from a local copy.

But, I don't think you can import `npm:leaflet/dist/leaflet.css` from`style.css`? It would be nice to add.

**Comment by mbostock** [comment] 2024-04-03 16:14
I think this is a duplicate of #416 in effect, although that issue only describes local imports, if we use our resolver infrastructure it would automatically support `npm:` imports, too.

**Closed** 2024-04-03 16:16 UTC
Labels: enhancement
