### ISSUE TITLE
Draft page status

### ISSUE THREAD

**Issue by Fil** [observablehq/framework#165] opened 2023-11-14 10:16 UTC
If a page's frontmatter has `status: draft`, (or not `status: published`, or `draft: true`, or whatever other syntax is common for static site generators), it should be shown by the dev server, with a visible "draft" overlay,  but should not be built.

**Comment by mbostock** [comment] 2024-03-04 05:40
Fixed in #891. Duplicate of #867.

**Closed by mbostock** 2024-03-04 05:40 UTC
Labels: enhancement
