### ISSUE TITLE
"No results" after refreshing site when using some parquet files

### ISSUE THREAD

**Issue by brichards920** [observablehq/framework#1470] opened 2024-06-17 16:57 UTC
When I write queries against parquet files tagged in the 'sql' preamble, I'm finding that they'll work as I'm starting to develop a report, but as I continue to iterate, they'll stop returning results entirely. 

It only seems to happen with medium+ sized files. I don't really see it with parquet files with only 100 or so rows, but after seeing it in some of my actual datasets I created a dummy dataset with 10,000 rows and just over 100 columns of dates, strings, and numbers, I was able to reproduce it with the dummy dataset too. 

I don't know 100%, but it seems like maybe it's related to the browser's cache? If I open up a private browsing window and a normal window, the private window seems OK while the normal window starts to fail. 

Here's the markdown file that corresponds to the situation that causes a failure for me. It's not typical for me to display 100+ columns in an Observable table, but I was seeing this error with smaller tables and I was trying to force it here. 

````

---
theme: dashboard
title: Example dashboard
toc: false
sql:
  dummy: ./data/dummy_data.parquet
---

```sql id=d1
select df_id::TEXT, num1, num5, str3 from dummy
```

```sql id=d2
select df_id, int1, int2, int3, num1, num2, num3, num4, num5, str1, str2, str3, str4, str5, dt1, dt2, dt3, dt4, 
	dt5, num6, num7, num8, num9, num10, num11, num12, num13, num14, num15, num16, num17, num18, num19, num20, 
	num21, num22, num23, num24, num25, num26, num27, num28, num29, num30, num31, num32, num33, num34, num35, 
	num36, num37, num38, num39, num40, num41, num42, num43, num44, num45, num46, num47, num48, num49, num50, 
	num51, num52, num53, num54, num55, num56, num57, num58, num59, num60, num61, num62, num63, num64, num65, 
	num66, num67, num68, num69, num70, num71, num72, num73, num74, num75, num76, num77, num78, num79, num80, 
	num81, num82, num83, num84, num85, num86, num87, num88, num89, num90, num91, num92, num93, num94, num95, 
	num96, num97, num98, num99, num100 from dummy
```

<div class="grid grid-cols-1">
  <div class="card">
    ${Inputs.table(d1)}
  </div>
</div>

<div class="grid grid-cols-1">
  <div class="card">
    ${Inputs.table(d2)}
  </div>
</div>

````

I haven't attached the parquet file since the file type doesn't seem to be supported for upload here. If there are any best practices you'd suggest for the parquet file that I should be using, like what version, compression, and so on, I can try that. I created this with a basic "write_parquet(dummyFrame, 'dummy_data.parquet')" call in R.

I don't think I experience the issue when I use .arrow files, so I have a workaround. But I wanted to check in here in case there's anything I can do to guarantee that the parquet files will continue to load after multiple refreshes.

**Comment by mbostock** [comment] 2024-06-17 17:22
Are you seeing any errors or failed requests in either the preview server console, or in your browser’s console?

**Comment by brichards920** [comment] 2024-06-17 18:54
I'm not getting any errors or anything in the console. I did notice that for the dataset that isn't loading, after clearing the cache and restarting the server, I'm seeing it send more GET requests to the problematic file the first time and fewer the second time, when the issue starts to present. I switched the hash to ellipses to save space below.

Load 1:
HEAD /_file/data/problematic.parquet?sha=...
GET /_file/data/problematic.parquet?sha=...
GET /_file/data/problematic.parquet?sha=...
GET /_file/data/problematic.parquet?sha=...
GET /_file/data/problematic.parquet?sha=...
GET /_file/data/problematic.parquet?sha=...

Load 2 (fewer calls to problematic.parquet):
HEAD /_file/data/problematic.parquet?sha=...
GET /_file/data/problematic.parquet?sha=...
GET /_file/data/problematic.parquet?sha=...
GET /_file/data/problematic.parquet?sha=...
GET /_file/data/problematic.parquet?sha=...

I'll continue to look into this to see if I can create a fully reproducible example. I've tried subsetting columns and rows of the files with issue to see if I can identify a specific column type or value in the data that is causing issues, but nothing has jumped out so far.

**Comment by brichards920** [comment] 2024-06-18 01:13
I kept checking into this to find a minimally reproducible example. I've tested the process below on two computers just to be sure. I grabbed the 'weather.parquet' file from this page: 

https://observablehq.com/@cmudig/duckdb-client

And I'm using this markdown file: 

````
---
theme: dashboard
title: Example dashboard
toc: false
sql:
  w: ./data/weather.parquet
---

```sql id=tbl2 display
select * from w limit 1
```
````

If I start the server with npm run dev, the page loads and everything looks great. 

![image](https://github.com/observablehq/framework/assets/10135679/932f0a7e-cc57-4430-bbe9-ab4e5cc7ca23)

Then if I adjust the query to:

````
select * from w limit 2
````

and save, the page live reloads and now I see two rows as expected. 

![image](https://github.com/observablehq/framework/assets/10135679/251b29e2-e822-4c5f-a8b5-5e485636dbfa)

However, then if I manually refresh the browser using ctrl+r, the table returns to "no results" and fails until I clear the cache. 

![image](https://github.com/observablehq/framework/assets/10135679/f62cc16e-5078-43cb-ac60-ad2f318bf722)

In addition, any query I run against the 'weather' dataset now fails with "no results" until I clear the cache - even restarting the server doesn't help. So it seems like my manual refresh might be the issue. 

I'm coming to framework having used Observable in the Quarto implementation, so I'm probably just refreshing the page out of habit. Is this a bug, or should I just 100% avoid using anything but the live preview?

**Comment by mbostock** [comment] 2024-06-18 01:50
I’m afraid I’m not able to reproduce.

https://github.com/observablehq/framework/assets/230541/324490bd-1689-4347-9040-e1ffd1e674d1

There shouldn’t be any issue with manually reloading the page. The fact that clearing the cache fixes the issue suggests that this may be a browser issue. If you’re willing, you could try updating or re-installing your browser, resetting your browser settings, uninstalling any extensions, or trying a different browser.

Since I can’t reproduce and can’t investigate further, I’m going to close this issue. But if you have any other hints, I’d be happy to take another look.

**Closed by mbostock** 2024-06-18 01:50 UTC
Labels: bug

**Comment by brichards920** [comment] 2024-06-18 03:07
Thanks for your help and for taking a look. Here's a similar setup on my screen with Chrome, Chrome in Incognito Mode, and Edge so you can see it live. 

https://github.com/observablehq/framework/assets/10135679/86ab9985-6668-443b-b16c-1b171b5751a6

**Comment by mbostock** [comment] 2024-06-18 03:44
Browser extensions are disabled in incognito tabs, so the fact that it works in the incognito tab suggests that a browser extension may be at fault. Did you try disabling browser extensions as I mentioned?

**Comment by brichards920** [comment] 2024-06-18 11:34
I just went through and double checked and reset both Chrome and Edge to their default settings and removed any extensions and unfortunately the problem persists.

I tried Firefox and oddly it does not seem to have the same problem.

Thanks again for checking into it. If I use arrow files instead the issue goes away, so I can continue to use framework.

**Comment by mbostock** [comment] 2024-06-18 11:37
Sorry for the trouble, and thanks for trying! I’ll report back here if we learn anything on this problem.

**Comment by brichards920** [comment] 2024-06-26 18:02
I'm just making a quick update here to note that the issue is likely related to duckdb-wasm: 

https://github.com/duckdb/duckdb-wasm/issues/1658

Users noted there as well that the issue could not be reproduced on a Mac.

**Comment by massyn** [comment] 2024-07-01 11:04
@brichards920 - I am experiencing the same issue.  I'd love to explore this a bit with you if I may.  

Some documentation seem to suggest this is a Chrome on Windows issue.  I did notice that when I run Observable in Firefox, or I start Chrome in Incognito mode, the problem goes away.  What browser / OS are you using?

How are you generating the Parquet file?  I am using Google BigQuery as my primary data source, with a Python data loader that uses Pandas to query BigQuery, and saving the Parquet file with `df.to_parquet()`

**Comment by brichards920** [comment] 2024-07-01 11:40
@massyn my situation sounds like it is the same - I'm on Windows and I can see the issue in Chrome and Edge. I confirmed this on two separate computers before posting the issue to try to rule out odd settings on one of them.

Using incognito mode in Chrome or using Firefox fixes the issue. That would be OK for me during development, but I share my outputs with a fair number of viewers who are all on a Windows/Chrome setup and it wouldn't be reasonable to ask them to use those workarounds.

I originally encountered the issue generating parquet files in R using arrow::write_parquet. When I was putting together this issue I was concerned that my workflow for generating the parquet files might be the problem, but I was able to reproduce it with 'weather.parquet' from here as well: https://observablehq.com/@cmudig/duckdb-client

**Comment by massyn** [comment] 2024-07-02 19:37
Hi @mbostock - I'd like to ask that you reopen this issue.  Both @brichards920 and myself are experiencing this issue, and it would help to have a place where we can work together to isolate this problem.

I have established a [test project](https://github.com/massyn/observablehq-test) using the `weather.parquet` file from your website, and I was able to produce the same behaviour as reported by @brichards920 .

The project can be viewed [here](http://static.massyn.net/observablehq-test/)

## When it shows up

* When using `Google Chrome` on `Windows`

## Workarounds

* Use `Firefox` (or any other browser that's not Chromium based)
* Run Google Chrome in `Incognito` mode.
* Use a different data file (`json` works, even thought the file is much bigger).

## Some observations

* Looking at the browser dev tools, I notice that on first load, the [weather.5d8516c3.parquet](http://static.massyn.net/observablehq-test/_file/data/weather.5d8516c3.parquet) file is read from the site, and it works.  On refresh, it reads the file from `disk cache`, and then it fails.
* On incognito mode, it also changes to "disk cache" but somehow keeps working.
* The behaviour experienced is similar to that mentioned here https://github.com/duckdb/duckdb-wasm/issues/1658.

It is likely that this is a DuckDB issue.

**Comment by mbostock** [comment] 2024-07-02 22:22
I can reopen the issue but it’s unlikely we’ll be able to fix it if it’s an issue in DuckDB-Wasm. Probably better to upvote and follow https://github.com/duckdb/duckdb-wasm/issues/1658.

**Comment by bjyberg** [comment] 2024-08-02 12:07
I'm not using Observable Framework, but I have been able to temporarily work around this in Observable Notebooks by cache busting until there is a better fix in place. Hopefully someone finds this useful. See example [here](https://observablehq.com/d/72281be2f13a0a72)

**Comment by mbostock** [comment] 2024-09-29 17:14
Here are some suggested workarounds to avoid caching of Parquet files on Windows: https://github.com/observablehq/framework/discussions/1691#discussioncomment-10790259
