### ISSUE TITLE
date and timestamp columns from sql represented as number

### ISSUE THREAD

**Issue by nieuwenhoven** [observablehq/framework#1524] opened 2024-07-18 18:55 UTC
example:

The following sql code block:

```sql
select current_date, current_timestamp
```
returns:
 
| current_date | current_timestamp |
| ------------- | ------------- |
| 1,721,260,800,000 | 1,721,322,677,842 |

**Comment by mbostock** [comment] 2024-07-18 18:59
Duplicate of https://github.com/observablehq/framework/issues/1376

**Closed by mbostock** 2024-07-18 18:59 UTC
Labels: bug
