### ISSUE TITLE
Commenting out a cell causes page to break

### ISSUE THREAD

**Issue by andyreagan** [observablehq/framework#1325] opened 2024-05-10 14:53 UTC
I have an element in the page like this:

```
  <div class="card">
    <h2>Calls remaining</h2>
    <span class="big">${[...data].filter(d => mutual_aid ? true : d.In_town).length.toLocaleString("en-US")}</span>
  </div>
```

but when I comment this out in markdown, like

```
  <!-- <div class="card">
    <h2>Calls remaining</h2>
    <span class="big">${[...data].filter(d => mutual_aid ? true : d.In_town).length.toLocaleString("en-US")}</span>
  </div> -->
```

I get an error in the console _after_ I refresh the page (it doesn't break on live reload). Then all elements lower down on the page don't work. Error looks like:

```
client.js:133 Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at define (client.js:133:24)
    at dashboard:183:1
```

and yes, you can see that the line in question from client.js

```
  const loading = root.classList.contains("observablehq--loading");
```

will get an error because the element id is not selected previously by `document.querySelector` because it's commented out from the html.

Seems like the issue is that the JS is sill picking up this element, and isn't respecting the html comment in the markdown the same way that the browser it (which doesn't render it).

Also seems pretty easy to reproduce. I'm loving framework and this tripped me up for longer than I'd like to admit!

**Comment by Fil** [comment] 2024-05-10 15:31
yes. but I think it's a duplicate of #375

**Closed by Fil** 2024-05-10 15:31 UTC
Labels: bug

**Comment by andyreagan** [comment] 2024-05-10 16:56
@Fil thanks. I had tried searching but that only has pictures, not the text, of the error message so that's why I didn't find it 😂 

this issue should help point searchers back over there!
