### ISSUE TITLE
Some Inline JS not rendering within html within md

### ISSUE THREAD

**Issue by a-lexwein** [observablehq/framework#900] opened 2024-02-23 00:41 UTC
If I put this in an html cell in an Observable notebook, the text is blue, but when I try in html with an .md file in Framework, the inline JS does not appear to render.
```
<p style="color: ${'blue'}">the color is ${'blue'}</p>
```
<img width="240" alt="image" src="https://github.com/observablehq/framework/assets/26701366/26d87824-66dc-42f7-b208-60670e6d9a1a">

Above was a clean minimal example, but what I'm really trying to do is port [this notebook](https://observablehq.com/@a-lexwein/bogdown@268) into Framework, and when I moved the `<style>` block at the bottom of the notebook to my Framework .md, the inline JS didn't seem like it was being evaluated. I haven't isolated a minimal example, but If you have an advice on a workaround, that'd be great.

Thanks!

**Comment by mbostock** [comment] 2024-02-23 01:06
We don’t currently support interpolation into attributes; you can only interpolate into text. Duplicate of #32. See #597 for some initial progress.

**Closed by mbostock** 2024-02-23 01:06 UTC
Labels: bug
