### ISSUE TITLE
observablehq.com/framework/sql suffers from unresolved duckdb-wasm cache issue

### ISSUE THREAD

**Issue by brichards920** [observablehq/framework#1702] opened 2024-09-30 18:31 UTC
I wanted to let you know that the observablehq.com/framework/sql documentation appears to suffer from the Windows Chrome/Edge cache issue coming from duckdb-wasm. It loads for the first time and fails on future page loads.

It works fine when using incognito mode. 

![image](https://github.com/user-attachments/assets/4515b2dc-6fe8-4b17-82cf-4b6debb65736)

**Comment by mbostock** [comment] 2024-09-30 19:11
Duplicate of #1470; workarounds in https://github.com/observablehq/framework/discussions/1691#discussioncomment-10790259. This is a bug in DuckDB-Wasm https://github.com/duckdb/duckdb-wasm/issues/1658 which they need to fix. I guess we could implement our own workaround, but I would rather than DuckDB-Wasm fix the underlying issue.

**Closed by mbostock** 2024-09-30 19:11 UTC
Labels: bug

**Comment by jtheisen** [comment] 2025-05-13 01:02
In the meantime, it would be helpful to have a warning in the Observable Platform docs that the parquet-duckdb-combination doesn't work properly. I reckon that a lot of users run into this, and the documentation pretends this works.
