### ISSUE TITLE
iMessage previews do not include dynamic content (like titles of dashboards)

### ISSUE THREAD

**Issue by jaanli** [observablehq/framework#1724] opened 2024-10-05 14:19 UTC
I am rebuilding my personal website using Observable Framework but seeing that if I send a link such as https://jaan.li/wanna-sauna to a friend, this is the result:

<img width="156" alt="image" src="https://github.com/user-attachments/assets/49455416-5919-4f36-873a-7b50aeac655e">

Is there a way to set:

- the title of the webpage that will be displayed in a search engine optimization-friendly way for Google or iMessage or Twitter? That would enable sharing the framework dashboards I build more widely
- updating a PNG or SVG preview of the dashboard associated with a webpage for display in iMessage - then someone may not even need to click the link to benefit from framework!

The source is here:

https://github.com/jaanli/jaan.li/blob/main/src/wanna-sauna.md

The correct title should be: "Wanna Sauna?"

I gave a talk at @duckdb's annual conference with several more examples recently: talk.onefact.org, and am curious what this would take. Related issue: https://github.com/observablehq/framework/issues/1378

**Comment by Fil** [comment] 2024-10-05 16:49
The part about the `<title>`  comes from your funky hero header wrapping `<h1>`. You can fix that by adding title in the front-matter:

```
---
title: Wanna Sauna
---
````

For the rest (images etc) it is a duplicate of #178.

**Closed by Fil** 2024-10-05 16:49 UTC
Labels: bug

**Comment by jaanli** [comment] 2024-10-06 14:02
Understood, thank you so much @Fil !!!
