### ISSUE TITLE
npm run dev error on windows

### ISSUE THREAD

**Issue by ericemc3** [observablehq/framework#809] opened 2024-02-15 16:13 UTC
after installing with npm init @observablehq on a windows 11 pc
npm run dev 
![image](https://github.com/observablehq/framework/assets/17407796/de2bdcf9-38ec-4c73-9050-23cfe4f2c758)

**Comment by mbostock** [comment] 2024-02-15 17:48
We don’t currently support Windows, but you can use the Windows Subsystem for Linux (WSL):

https://learn.microsoft.com/en-us/windows/wsl/about

**Comment by mbostock** [comment] 2024-02-15 17:48
Duplicate of #809.

**Closed by mbostock** 2024-02-15 17:48 UTC
Labels: bug
