### ISSUE TITLE
Vi and emacs don't properly live update in preview

### ISSUE THREAD

**Issue by mythmon** [observablehq/framework#563] opened 2024-01-19 15:50 UTC
Ambassador Martien [reports](https://observable-community.slack.com/archives/C06E30AF761/p1705677466167639?thread_ts=1705677466.167639&cid=C06E30AF761) that when saving files using vim and emacs in their default configurations, the CLI does not properly live update and instead shows an error about "file no longer exists".

> Question: (I’m new to yarn):
> - when I use vi or emacs to edit, say, index.md , yarn says “file no longer exists: /index.md”, and the page in Safari does not update;
> - when I edit a copy of index.md and use that to overwrite index.md, yarn sees the update and updates the browser page.
>
> What editor should I use?

> I think I found it. In vi , :set nowritebackup) :
> - inode stays the same;
> - only modify and change timestamps change. Access and birth remain the same.

**Comment by eitanlees** [comment] 2024-03-06 15:58
For Neovim I added the following to `~/.config/nvim/init.lua`

```
vim.opt.backupcopy = 'yes'
```

and that alleviated the issue.

**Comment by Fil** [comment] 2024-03-23 16:37
fixed with #1127

**Comment by mbostock** [comment] 2024-03-23 16:45
I don’t see it fixed in vi. Can you confirm? When I save changes in vi, the file is written, but the preview server doesn’t see anything as changed, so I have to reload in the browser.

**Comment by mbostock** [comment] 2024-03-23 16:48
It seems like the _first_ save in vi triggers a reload, but subsequent saves (after the `file no longer exists` message) do not trigger updates.

**Comment by mbostock** [comment] 2024-03-23 16:51
I think the problem is a race condition where the await for lazy config #695 here `handleWatch(socket, req, await this._readConfig())` means we can miss the _hello_↑ message that is sent immediately upon connect.

**Comment by Fil** [comment] 2024-03-23 16:57
You're right, it's still failing.

**Closed** 2024-03-23 17:44 UTC
Labels: bug

**Comment by nelsonspbr** [comment] 2024-06-11 15:48
Oh wow, I spent more time than I'd like to admit thinking why Observable framework doesn't react to changes in a simple file. I was using Vim to edit the file.

**Comment by mbostock** [comment] 2024-06-11 16:17
@nelsonspbr This was fixed a few months ago. Are running an old version of Framework? If you’re still experiencing a problem with the latest version of Framework, please file a new issue with steps to reproduce. I’ve just tested locally using vi and live preview is working as expected. Thank you.
